# Generated by Django 5.0.6 on 2026-01-14 05:07

from django.conf import settings
from django.db import migrations, models


def add_constraint_if_table_exists(apps, schema_editor):
    """
    Create OrganizationMember table if it doesn't exist, then add constraint.
    This handles cases where migration 0001 partially failed or table is missing.
    """
    db_connection = schema_editor.connection
    
    # Check if table exists
    table_exists = False
    try:
        with db_connection.cursor() as cursor:
            if db_connection.vendor == 'postgresql':
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM information_schema.tables 
                        WHERE table_schema = 'public' 
                        AND table_name = 'organization_organizationmember'
                    );
                """)
                table_exists = cursor.fetchone()[0]
            elif db_connection.vendor == 'sqlite':
                cursor.execute("""
                    SELECT name FROM sqlite_master 
                    WHERE type='table' AND name='organization_organizationmember';
                """)
                table_exists = cursor.fetchone() is not None
            else:
                table_exists = False
    except Exception:
        table_exists = False
    
    # If table doesn't exist, create it first
    if not table_exists:
        try:
            OrganizationMember = apps.get_model('organization', 'OrganizationMember')
            schema_editor.create_model(OrganizationMember)
        except Exception as e:
            import logging
            logger = logging.getLogger(__name__)
            logger.error(f"Could not create OrganizationMember table: {str(e)}")
            raise
    
    # Table exists, try to add constraint
    try:
        OrganizationMember = apps.get_model('organization', 'OrganizationMember')
        
        # Check if constraint already exists
        constraint_exists = False
        if db_connection.vendor == 'postgresql':
            with db_connection.cursor() as cursor:
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM pg_constraint 
                        WHERE conname = 'unique_active_session_per_user'
                    );
                """)
                constraint_exists = cursor.fetchone()[0]
        
        if not constraint_exists:
            # Add constraint using Django's schema editor
            constraint = models.UniqueConstraint(
                fields=['user'],
                condition=models.Q(is_session_active=True),
                name='unique_active_session_per_user'
            )
            schema_editor.add_constraint(OrganizationMember, constraint)
    except Exception as e:
        # If constraint addition fails, log but don't fail migration
        # This handles cases where:
        # 1. Constraint can't be added (e.g., multiple active sessions exist)
        # 2. Database doesn't support partial unique constraints
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"Could not add constraint unique_active_session_per_user: {str(e)}")
        logger.warning("Please ensure all users have at most one active session before running this migration.")
        # Don't raise - allow migration to continue


def remove_constraint_if_exists(apps, schema_editor):
    """
    Safely remove constraint if it exists.
    """
    try:
        OrganizationMember = apps.get_model('organization', 'OrganizationMember')
        constraint = models.UniqueConstraint(
            fields=['user'],
            condition=models.Q(is_session_active=True),
            name='unique_active_session_per_user'
        )
        schema_editor.remove_constraint(OrganizationMember, constraint)
    except Exception:
        # If constraint doesn't exist, that's fine
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            add_constraint_if_table_exists,
            reverse_code=remove_constraint_if_exists,
        ),
    ]
