# Generated by Django 5.0.6 on 2026-02-23 08:09

from django.conf import settings
from django.db import migrations, models


def check_and_add_constraint_safely(apps, schema_editor):
    """
    Safely add constraint only if it doesn't already exist.
    This handles cases where constraint was already added by migration 0002.
    """
    db_connection = schema_editor.connection
    
    # Always check if constraint exists first - if it does, skip entirely
    constraint_exists = False
    try:
        # Use a new cursor to avoid transaction issues
        with db_connection.cursor() as cursor:
            if db_connection.vendor == 'postgresql':
                # Check in pg_constraint for the constraint name
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'unique_active_session_per_user'
                        AND conrelid = (
                            SELECT oid FROM pg_class 
                            WHERE relname = 'organization_organizationmember'
                        )
                    );
                """)
                result = cursor.fetchone()
                constraint_exists = result[0] if result else False
            elif db_connection.vendor == 'sqlite':
                # SQLite stores unique constraints as indexes
                cursor.execute("""
                    SELECT name FROM sqlite_master 
                    WHERE type='index' AND name='unique_active_session_per_user';
                """)
                constraint_exists = cursor.fetchone() is not None
            else:
                constraint_exists = False
    except Exception as e:
        # If check fails, assume constraint doesn't exist
        # But we'll catch the error when trying to add it
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"Could not check if constraint exists: {str(e)}")
        constraint_exists = False
    
    if constraint_exists:
        # Constraint already exists (probably added by migration 0002), skip
        import logging
        logger = logging.getLogger(__name__)
        logger.info("Constraint unique_active_session_per_user already exists, skipping.")
        return
    
    # Constraint doesn't exist, try to add it
    # Wrap in try-except to handle any errors gracefully
    try:
        OrganizationMember = apps.get_model('organization', 'OrganizationMember')
        constraint = models.UniqueConstraint(
            fields=['user'],
            condition=models.Q(is_session_active=True),
            name='unique_active_session_per_user'
        )
        schema_editor.add_constraint(OrganizationMember, constraint)
    except Exception as e:
        # If constraint addition fails, check if it's because constraint already exists
        error_msg = str(e).lower()
        if 'already exists' in error_msg or 'duplicate' in error_msg or 'relation' in error_msg:
            # Constraint already exists, that's fine - skip
            import logging
            logger = logging.getLogger(__name__)
            logger.info(f"Constraint unique_active_session_per_user already exists: {str(e)}")
            return
        
        # Other error - log but don't fail migration
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"Could not add constraint unique_active_session_per_user: {str(e)}")
        # Don't raise - allow migration to continue


def remove_constraint_if_exists(apps, schema_editor):
    """
    Safely remove constraint if it exists.
    """
    try:
        OrganizationMember = apps.get_model('organization', 'OrganizationMember')
        constraint = models.UniqueConstraint(
            fields=['user'],
            condition=models.Q(is_session_active=True),
            name='unique_active_session_per_user'
        )
        schema_editor.remove_constraint(OrganizationMember, constraint)
    except Exception:
        # If constraint doesn't exist, that's fine
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationmember_unique_active_session_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            check_and_add_constraint_safely,
            reverse_code=remove_constraint_if_exists,
        ),
    ]
