# Generated by Django 5.0.6 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_pending_phone_user_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorsAllowedOrigin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CORS Allowed Origin",
                "verbose_name_plural": "CORS Allowed Origins",
                "ordering": ("origin",),
            },
        ),
    ]
