# Generated by Django 5.0.6 on 2026-07-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_ssoauthorizationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOAllowedRedirectURI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=120)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SSO Allowed Redirect URI',
                'verbose_name_plural': 'SSO Allowed Redirect URIs',
                'ordering': ('client_id', 'redirect_uri'),
                'unique_together': {('client_id', 'redirect_uri')},
            },
        ),
    ]
