# Generated by Django 5.0.6 on 2026-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passkeys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpasskey",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]

